name: "Build - action"

on: [push, pull_request]

jobs:
  build-docker-image:
    name: "GRA Docker"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build.bash
        env:
          BLD_DOCKER_IMAGE: gra
          CR_OWNER: mcld
          CR_PASSWORD: ${{secrets.CR_PASSWORD}}
          CR_USER: ${{secrets.CR_USER}}
          GHCR_PAT: ${{secrets.GHCR_PAT}}
          GHCR_USER: ${{secrets.GHCR_USER}}
        run: ./build.bash
