name: docker lock verify
run-name: ${{ github.actor }} is running docker lock verify

on:
  pull_request:

jobs:
  build-docker-image:
    name: "GRA Docker Lock Verify"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-lock verify
        run: docker run -v $PWD:/run safewaters/docker-lock lock verify
