name: "Docker Lock Verify - action"

on:
  pull_request:
  schedule:
    - cron: '5 5 * * 5'

jobs:
  build-docker-image:
    name: "GRA Docker Lock Verify"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-lock verify
        run: docker run -v $PWD:/run safewaters/docker-lock lock verify
